esphome:
  name: rfm69x-sample
  friendly_name: RFM69X Sample
  comment: "Sample configuration for RFM69X custom component"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: DEBUG
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

#  # Enable fallback hotspot (no captive portal) in case wifi connection fails#
#  ap:
#    ssid: ${device_name}
#    password: !secret ota_password
#    ap_timeout: 15s

#3esp32_ble_tracker:
#bluetooth_proxy:

web_server:
  port: 80

#time:
 # - platform: homeassistant
 #   id: homeassistant_time

captive_portal:

# Here we define the existence of a custom component we developed
external_components:
  - source: ./components/
    components: [rfm69x, rf_sniffer]
    refresh: always


# Define the SPI bus for the RFM69W
spi:
  clk_pin: GPIO18
  miso_pin: GPIO19
  mosi_pin: GPIO23

rfm69x:
  id: rfm69x_component
  cs_pin: GPIO5

rf_sniffer:
  id: sniffer_component
  radio_id: rfm69x_component

